# Generated by Django 4.1.2 on 2022-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('disc', models.TextField()),
                ('image', models.ImageField(upload_to='movie_images')),
                ('year', models.IntegerField()),
            ],
        ),
    ]
